@jwt1 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDM2NTg0OTV9.oKR51b0g52lSbCs0P0bzvKiUakwuZ5k_Vsxl9HXafWg

@jwt2 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMzMDU2MTB9.pxciGEUw3B37YmNuYO6R3uoeQbogeJlM0Eec1qEAi0U

@jwt3 = hbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMzMDU2MTB9.pxciGEUw3B37YmNuYO6R3uoeQbogeJlM0Eec1q

###Products Index

GET http://localhost:3000/products
Authorization: Bearer {{jwt2}}

###Products Show

GET http://localhost:3000/products/8
Authorization: Bearer {{jwt1}}

###Products Create

POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer {{jwt1}}

{
  "name": "Packers Papyrus Font",
  "price": 12,
  "description": "Truly a great font",
  "inventory": 160,
  "supplier_id": 1
}

###Products Update

PATCH http://localhost:3000/products/8
Content-Type: application/json

{
  "inventory": 6
}

###Products Destroy

DELETE http://localhost:3000/products/6

###Users Index

GET http://localhost:3000/users

###Users Create
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Mester Bester",
  "email": "mester.bester@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create LOGIN LOGIN LOGIN LOGIN LOGIN LOGIN

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "tester.fester@gmail.com",
  "password": "password"
}

### Order Index

GET http://localhost:3000/orders
Authorization: Bearer {{jwt1}}

### Order Create
POST http://localhost:3000/orders
Authorization: Bearer {{jwt1}}

### Order Show

GET http://localhost:3000/orders/8
Authorization: Bearer {{jwt1}}

###Cart Index

GET http://localhost:3000/carted_products
Authorization: Bearer {{jwt2}}

###Cart Create

POST http://localhost:3000/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt1}}

{
  "product_id": 1,
  "quantity": 4
}