@jwt1 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDMzMDU1ODR9.K0Ycc5cmS92GJm-VA5m0ZgXgfhrMIpDrYEq_tHTIgxE

@jwt2 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMzMDU2MTB9.pxciGEUw3B37YmNuYO6R3uoeQbogeJlM0Eec1qEAi0U

@jwt3 = hbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMzMDU2MTB9.pxciGEUw3B37YmNuYO6R3uoeQbogeJlM0Eec1q

###Products Index

GET http://localhost:3000/products
Authorization: Bearer {{jwt2}}

###Products Show

GET http://localhost:3000/products/8
Authorization: Bearer {{jwt1}}

###Products Create

POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer {{jwt1}}

{
  "name": "Packers Papyrus Font",
  "price": 12,
  "description": "Truly a great font",
  "inventory": 160,
  "supplier_id": 1
}

###Products Update

PATCH http://localhost:3000/products/8
Content-Type: application/json

{
  "inventory": 6
}

###Products Destroy

DELETE http://localhost:3000/products/6

###Users Index

GET http://localhost:3000/users

###Users Create
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Mester Bester",
  "email": "mester.bester@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "bester.tester@gmail.com",
  "password": "password"
}

### Order Index

GET http://localhost:3000/orders
Authorization: Bearer {{jwt2}}

### Order Create
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer {{jwt2}}

{
  "product_id": 2,
  "quantity": 7
}

### Order Show

GET http://localhost:3000/orders/8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDMyMjcwNDl9.yP8EKXbz-ziRuQsS2pEN3ry4PP7GVSsTwWZolJDw9tE
