###Products Index

GET http://localhost:3000/products

###Products Show

GET http://localhost:3000/products/8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMxNDE5NDN9.MU4LV2X51C2-Kk9wD1yizmdSnaMrusb57eod0efRLdM

###Products Create

POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMxNDE5NDN9.MU4LV2X51C2-Kk9wD1yizmdSnaMrusb57eod0efRLdM

{
  "name": "Packers Special Teams",
  "price": 160,
  "description": "It really was special :(",
  "inventory": 13,
  "supplier_id": 1
}

###Products Update

PATCH http://localhost:3000/products/8
Content-Type: application/json

{
  "inventory": 6
}

###Products Destroy

DELETE http://localhost:3000/products/6

###Users Create
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Bester Tester",
  "email": "bester.tester@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "bester.tester@gmail.com",
  "password": "password"
}

### Order Index

GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMyMjcxNzd9.jzA9-IpLmGHG2dLZEEzjeQicr2CR9YK6Q8RbcMO8Jio

### Order Create
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMyMjcxNzd9.jzA9-IpLmGHG2dLZEEzjeQicr2CR9YK6Q8RbcMO8Jio

{
  "product_id": 3,
  "quantity": 6
}

### Order Show

GET http://localhost:3000/orders/8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDMyMjcwNDl9.yP8EKXbz-ziRuQsS2pEN3ry4PP7GVSsTwWZolJDw9tE
